faiss_retriever:
  type: dense
  module: retrieval.retrievers.dense
  class: DenseRetriever
  config:
    metric: cosine

bm25_retriever:
  type: bm25
  module: retrieval.retrievers.bm25
  class: BM25Retriever

hybrid_retriever:
  type: hybrid
  module: retrieval.retrievers.hybrid
  class: HybridRetriever

embedder:
  type: sentence_transformers
  module: ingestion.embeddings.models.sentence_transformers
  class: SentenceTransformerEmbedder
  config:
    model_name: all-MiniLM-L6-v2

cross_encoder_reranker:
  type: cross_encoder
  module: retrieval.retrievers.reranker.cross_encoder
  class: CrossEncoderReranker
  config:
    model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    device: "cuda"

chunker:
  type: langchain
  module: ingestion.dataprep.chunkers.langchain_chunker
  class: LangChainChunker
  config:
    chunk_size: 1500
    chunk_overlap: 150

generator:
  type: openrouter
  module: generation.models.adapters.openrouter
  class: OpenRouterAdapter
  config:
    api_url: https://openrouter.ai/api/v1
    model: nvidia/nemotron-nano-9b-v2:free
    temperature: 0.0
    max_tokens: 1000

cleaner:
  type: normal_cleaner
  module: ingestion.dataprep.cleaners.pipeline
  class: Cleaner

annotator:
  type: page_annotator
  module: ingestion.dataprep.annotators.pipeline
  class: PageLegalAnnotator