mlops:
  backend: mlflow

mlflow:
  tracking_uri: "http://localhost:5050"
  experiment_name: "document_ingestion"

  artifact_uri: "file://$(pwd)/orchestrations/mlflow_artifacts"

  default_tags:
    team: "legal-rag"
    project: "legal-document-pipeline"
