name: CI/CD to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME:    ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD:    ${{ secrets.ACR_PASSWORD }}
  RESOURCE_GROUP:  ${{ secrets.RESOURCE_GROUP }}
  ENVIRONMENT:     ${{ secrets.ENVIRONMENT }}
  CONTAINER_APP:   ${{ secrets.CONTAINER_APP }}
  IMAGE_NAME:      veritly-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username:     ${{ secrets.ACR_USERNAME }}
        password:     ${{ secrets.ACR_PASSWORD }}
  
    - name: Build and push image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64
        tags: |
          ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  
  

    - name: Deploy to Container Apps
      run: |
        az containerapp update \
          --name $CONTAINER_APP \
          --resource-group $RESOURCE_GROUP \
          --environment $ENVIRONMENT \
          --image $ACR_LOGIN_SERVER/$IMAGE_NAME:$TAG

    - name: Show URL
      run: |
        URL=$(az containerapp show \
          --name $CONTAINER_APP \
          --resource-group $RESOURCE_GROUP \
          --query properties.configuration.ingress.fqdn -o tsv)
        echo "🚀 App deployed at: https://$URL"
